version: '3.8'

services:
  postgres02:
    image: postgres:16
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: devops
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"
    volumes:
      - postgres_data_2:/var/lib/postgresql/data

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydb
      MYSQL_USER: devops
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data_1:/var/lib/mysql

  mongodb:
    image: mongo:4.0
    environment:
      MONGO_INITDB_ROOT_USERNAME: devops
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data_1:/data/db

  milvus-standalone:
    image: milvusdb/milvus:latest
    command: ["milvus", "run", "standalone"]
    environment:
      ETCD_ENDPOINTS: etcd:2379
      MINIO_ADDRESS: minio:9000
    ports:
      - "19530:19530"  # Milvus server port
      - "9091:9091"    # Milvus RESTful API port
    volumes:
      - milvus_data:/var/lib/milvus
    depends_on:
      - etcd
      - minio

  etcd:
    image: quay.io/coreos/etcd:v3.5.0
    command: etcd -advertise-client-urls=http://etcd:2379 -listen-client-urls=http://0.0.0.0:2379
    ports:
      - "2379:2379"
    volumes:
      - etcd_data:/etcd_data

  minio:
    image: minio/minio:latest
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - "9000:9000"    # MinIO API port
      - "9001:9001"    # MinIO Console port
    volumes:
      - minio_data:/data
  attu:
    image: zilliz/attu:latest
    ports:
      - "8000:3000"  # Attu web interface
    environment:
      MILVUS_URL: milvus-standalone:19530
    depends_on:
      - milvus-standalone 

volumes:
  postgres_data_2:
  mysql_data_1:
  mongodb_data_1:
  milvus_data:
  etcd_data:
  minio_data:
