version: '3.8'

services:
  postgres02:
    image: postgres:16
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: devops
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"
    volumes:
      - postgres_data_2:/var/lib/postgresql/data
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydb
      MYSQL_USER: devops
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data_1:/var/lib/mysql
  mongodb:
    image: mongo:4.0
    environment:
      MONGO_INITDB_ROOT_USERNAME: devops
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data_1:/data/db      
volumes:
  postgres_data_2:
  mysql_data_1:
  mongodb_data_1:
